import toRob from "@/components/assets/house.jpg"
import toIvan from "@/components/assets/ivan.jpg"
import toJosh from "@/components/assets/toJosh.jpg"
import coSho from "@/components/assets/sho.jpg"
import apJosh1 from "@/components/assets/apJosh1.jpg"
import apMit1 from "@/components/assets/apMit1.jpg"
import stJosh1 from "@/components/assets/stJosh1.jpg"
import apEm1 from "@/components/assets/ap-em-1.jpg"
import stJosh2 from "@/components/assets/stJosh2.jpg"
import dzor from "@/components/assets/dzor.jpg"

const properties = [
  {
    id: 1,
    title: 'Modern Townhouse',
    description: 'Spacious 4-bedroom apartment for rent. Fully Furnished',
    price: '$5,200',
    location: 'Airport Residential Area',
    type: 'Townhouse',
    bedrooms: 4,
    bathrooms: 5,
    area: '500 sqm',
    image: toIvan,
    meqasa: "https://meqasa.com/filter3/one?p=397620",
  },
  {
    id: 2,
    title: 'Luxurious Townhouse',
    description: '4-bedroom Townhouse with mordern features. Fully Furnished',
    price: '$800,000',
    location: 'Cantonments',
    type: 'Townhouse',
    bedrooms: 4,
    bathrooms: 4,
    area: '500 sqm',
    image: toRob,
    meqasa: "https://meqasa.com/filter3/one?p=399191",
  },
  {
    id: 3,
    title: 'Brand new Townhouse',
    description: 'Great architectural design 3-bedroom. Furnised',
    price: '$3,500',
    location: 'East Legon',
    type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 3,
    area: '500 sqm',
    image: toJosh,
    meqasa: "https://meqasa.com/filter3/one?p=398302",
  },
  {
    id: 4,
    title: 'Modern Commercial Space',
    description: 'Great location for your business',
    price: '$3,000',
    location: 'Cantonments',
    type: 'Offices',
    bedrooms: 2,
    bathrooms: 2,
    area: '103 sqm',
    image: coSho,
    meqasa: "https://meqasa.com/filter3/one?p=397740",
  },
  {
    id: 5,
    title: 'Brand new mordern Apartment',
    description: 'Spacious 1-bedroom apartment with great view',
    price: '$1,400',
    location: 'Labone',
    type: 'Apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: '77 sqm',
    image: apJosh1,
    meqasa: "https://meqasa.com/filter3/one?p=397615",
  },
  {
    id: 6,
    title: 'Nice Apartment',
    description: 'Spacious 2-bedroom apartment with lots spacious parking.',
    price: '$1,465',
    location: 'Shiashie',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 3,
    area: '150 sqm',
    image: apMit1,
    meqasa: "https://meqasa.com/filter3/one?p=398173",
  },
  {
    id: 7,
    title: 'Standalone House',
    description: 'Get a spacious 6-bedroom house for rent at East legon',
    price: '$2,600',
    location: 'East legon(Trassaco)',
    type: 'House',
    bedrooms: 6,
    bathrooms: 7,
    area: '600 sqm',
    image: stJosh1,
    meqasa: "https://meqasa.com/filter3/one?p=397613",
  },
  {
    id: 8,
    title: 'Modern Apartment',
    description: 'Spacious 1-bedroom apartment. Fully furnished',
    price: '$1,600',
    location: 'Labone',
    type: 'Apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: '65 sqm',
    image: apEm1,
    meqasa: "https://meqasa.com/filter3/one?p=398287",
  },
  {
    id: 9,
    title: 'Your standalone house for rent',
    description: 'Great 4-bedroom furnished for rent',
    price: '$3,500',
    location: 'East legon',
    type: 'House',
    bedrooms: 4,
    bathrooms: 4,
    area: '400 sqm',
    image: stJosh2,
    meqasa: "https://meqasa.com/filter3/one?p=397608",
  },
  {
    id: 10,
    title: 'Modern Apartment',
    description: 'Spacious 2-bedroom apartment with a communal pool',
    price: '$1,000',
    location: 'Dzorwulu',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: '77 sqm',
    image: dzor,
    meqasa: "https://meqasa.com/filter3/one?p=397619",
  },
]

export default properties
